name: Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  push_docker_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push problem-sphere Docker Image
      run: |
        make build-problem NAME=sphere
        make push-problem NAME=sphere

    - name: Push problem-elliptic Docker Image
      run: |
        make build-problem NAME=elliptic
        make push-problem NAME=elliptic

    - name: Push problem-rastrigin Docker Image
      run: |
        make build-problem NAME=rastrigin
        make push-problem NAME=rastrigin

    - name: Push problem-rosenbrock Docker Image
      run: |
        make build-problem NAME=rosenbrock
        make push-problem NAME=rosenbrock

    - name: Push indicator-best Docker Image
      run: |
        make build-indicator NAME=best
        make push-indicator NAME=best

    - name: Push indicator-hypervolume Docker Image
      run: |
        make build-indicator NAME=hypervolume
        make push-indicator NAME=hypervolume
